local deftest = require "deftest.deftest"

local test_boom = require "test.test_boom"
local test_systems = require "test.test_systems"
local test_gameobject = require "test.test_gameobject"
local test_collisions = require "test.test_collisions"

function init(self)
	timer.delay(0, false, function()
		deftest.add(test_boom)
		deftest.add(test_systems)
		deftest.add(test_gameobject)
		deftest.add(test_collisions)
		deftest.run({ coverage = { enabled = true }, pattern = nil })
	end)
end

