go.property("group", hash("area"))
go.property("area_mask", true)
go.property("static_mask", false)

local collisions = require "boom.internal.collisions"

function init(self)
	physics.set_group("#collisionobject", self.group)
	physics.set_maskbit("#collisionobject", hash("area"), self.area_mask)
	physics.set_maskbit("#collisionobject", hash("static"), self.static_mask)
end

function on_message(self, message_id, message, sender)
	collisions.on_message(message_id, message, sender)
end
